SELECT YEAR, JVN_NATION1, JVN_NATION2, JVN_NATION3, JVN_NATION4, JVN_NATION5, 
JVN_NATION6, JVN_NATION7, JVN_NATION8, JVN_NATION9, JVN_NATION10, JVN_NATION11, JVN_NATION0 
FROM WARROOM_CASE_NATION_ALL ORDER BY YEAR