BEGIN MERGE
INTO    WARROOM_CASE_GROUPYEAR_ALL d
USING   (
        	SELECT RECEIVE_YEAR, N, Y, NLL, N+Y+NLL AS TOTAL, SYSTIMESTAMP FROM(
				SELECT * FROM 
					(SELECT JVN_ID, RECEIVE_YEAR, NVL2(CTRL_STATUS,CTRL_STATUS,0) AS stat  FROM VDTL_CMST_CASE_MAIN_HD2 WHERE RECEIVE_YEAR = to_char(sysdate, 'YYYY')+543 ) 
					PIVOT(
					    COUNT(JVN_ID) 
					    FOR stat
					    IN ( 
					        'N' N,
					        'Y' Y,
					         0 NLL
					    )
					)
			)
        ) s
ON      (s.RECEIVE_YEAR = d.YEAR)
WHEN NOT MATCHED THEN
INSERT  (YEAR, ENSURE, CONTROL, NOCONTROL, TOTAL, UPDATE_TIME) 
VALUES  (RECEIVE_YEAR, N, Y, NLL,  N+Y+NLL, SYSTIMESTAMP)
WHEN MATCHED THEN
UPDATE
SET     ENSURE = N, 
        CONTROL = Y, 
        NOCONTROL = NLL, 
        TOTAL = TOTAL, 
        UPDATE_TIME = SYSTIMESTAMP; END;